# currently docker daemon needs sudo
# as of version 18.06
sudo: required

services:
  - docker

# series of commands exc before tests run
before_install:
  - docker build -t bennettdixon16/spadefish_gitapp ./

script:
  - echo 'testing'
  # - docker run bennettdixon16/spadefish_gitapp python3 -m api.v1.tests.test_base_model
