# docker-compose up --build
# in order to add latest changes to the img
version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # TODO should be using secrets not env
    environment:
      - GITHUB_OAUTH_CLIENT_ID
      - GITHUB_OAUTH_CLIENT_SECRET
      # Set to one for local testing
      - OAUTHLIB_INSECURE_TRANSPORT
    ports:
      - "5005:5000"
    command: ["python3", "-u", "-m", "api.v1.app"]
    # DEV
  #frontend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.frontend
  #  ports:
  #    - "8080:8080"
